runserver:
	sudo apt-get install php7.2 php7.2-mbstring php7.2-mysql php7.2-intl php7.2-xml composer
	composer install --no-scripts
	cp .env.example .env
	php artisan key:generate
	php artisan serve

conf-git-reni:
	git config --global user.name "renissonsilva"
	git config --global user.email "renissonx@gmail.com"

conf-git-pedro:
	git config --global user.name "pphenriquesm"
	git config --global user.email "pphenriue543@gmail.com"

conf-git-gui:
	git config --global user.name "GuiLira"
	git config --global user.email "liraguilherme252@gmail.com"

conf-git-math:
	git config --global user.name "gmatheus66"
	git config --global user.email "gmatheus66@hotmail.com"

conf-git-aline:
	git config --global user.name "alinevenceslau"
	git config --global user.email "alineepecris79@gmail.com"

